//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsoftApp.FailiDannih
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public int ExecutorID { get; set; }
        public string ExecutorTekst { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime Deadline { get; set; }
        public double Difficulty { get; set; }
        public int Time { get; set; }
        public string Status { get; set; }
        public string WorkType { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Executor Executor { get; set; }
    }
}
